language: cpp

matrix:
 include:
  - os: osx
    compiler: clang
    env:
     - QT_BASE=510

before_install:

install:
  brew install qt5;
  brew link --force qt5;

script:
  - qmake -v
  - qmake -r
  - make

notifications:
  email: false