language: cpp

matrix:
 include:
  - os: osx
    compiler: clang
    env:
     - QT_BASE=510
     - FILE=tikzit-osx.dmg
  - os: osx
    osx_image: xcode6.4
    env:
      - QT_BASE=510
      - FILE=tikzit-osx-yosemite.dmg 

before_install:

install:
  brew install qt5;
  brew link --force qt5;

script:
  - qmake -v
  - qmake -r
  - make
  - macdeployqt tikzit.app -dmg
  - curl --upload-file tikzit.dmg https://transfer.sh/$FILE

notifications:
  email: false