language: cpp

branches:
  only:
    - master

matrix:
 include:
  - os: osx
    compiler: clang
    env:
      - FILE=tikzit-osx.dmg
      - QTVER=511
      - DEPLOY_TIKZIT=1
  # - os: osx
  #   compiler: clang
  #   env:
  #     - FILE=tikzit-osx-mountain.dmg
  #     - QTVER=56
  #     - DEPLOY_TIKZIT=1

before_install:
  # - '[[ "$TRAVIS_OS_NAME" != osx || "$QTVER" != 56 ]] || curl https://raw.githubusercontent.com/GiovanniBussi/macports-ci/master/macports-ci > macports-ci'
  # - '[[ "$TRAVIS_OS_NAME" != osx || "$QTVER" != 56 ]] || source macports-ci install'



install:
  - '[[ "$TRAVIS_OS_NAME" != osx || "$QTVER" != 511 ]] || brew update'
  - '[[ "$TRAVIS_OS_NAME" != osx || "$QTVER" != 511 ]] || brew install qt5'
  - '[[ "$TRAVIS_OS_NAME" != osx || "$QTVER" != 511 ]] || brew link --force qt5'
  - '[[ "$TRAVIS_OS_NAME" != osx || "$QTVER" != 511 ]] || brew install poppler --with-qt'
  # - '[[ "$TRAVIS_OS_NAME" != osx || "$QTVER" != 56 ]] || sudo port -N -k install qt56'
  # - '[[ "$TRAVIS_OS_NAME" != osx || "$QTVER" != 56 ]] || export PATH=/opt/local/libexec/qt5/bin:$PATH'

script:
  - qmake -v
  - qmake -r
  - make
  - '[[ "$TRAVIS_OS_NAME" != osx ]] || (chmod +x deploy-osx.sh && ./deploy-osx.sh && mv tikzit.dmg $FILE)'
  - '[[ "$DEPLOY_TIKZIT" != 1 ]] || curl --upload-file $FILE https://transfer.sh/$FILE'

notifications:
  email: false
