language: cpp

env:
  - DEPLOY_TIKZIT=0

matrix:
 include:
  - os: osx
    compiler: clang
    env:
      - FILE=tikzit-osx.dmg
    cache:
      directories:
        - $HOME/Library/Caches/Homebrew
  - os: linux
    dist: trusty
    env:
      - FILE=tikzit-linux.tar.gz
      - PPA=beineri/opt-qt-5.10.1-trusty

before_install:
  - '[[ "$TRAVIS_OS_NAME" != linux || -z "$PPA" ]] || sudo add-apt-repository -y ppa:$PPA'
  - '[[ "$TRAVIS_OS_NAME" != linux ]] || sudo apt-get -qy update'

install:
  - '[[ "$TRAVIS_OS_NAME" != osx ]] || brew install qt5'
  - '[[ "$TRAVIS_OS_NAME" != osx ]] || brew link --force qt5'
  - '[[ "$TRAVIS_OS_NAME" != linux ]] || sudo apt-get -qy install qt510base qt510xmlpatterns'
  - '[[ "$TRAVIS_OS_NAME" != linux ]] || . /opt/qt510/bin/qt510-env.sh'

script:
  - qmake -v
  - qmake -r
  - make
  - '[[ "$TRAVIS_OS_NAME" != osx ]] || (macdeployqt tikzit.app -dmg && mv tikzit.dmg $FILE)'
  - '[[ "$DEPLOY_TIKZIT" != 1 ]] || curl --upload-file $FILE https://transfer.sh/$FILE'

notifications:
  email: false